name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Print current directory
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Build static files
        run: npm run build
        working-directory: ./


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
