name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: 16.x    
      - run: npm ci
        working-directory: ./    
      - run: npm run build -- --mongo-uri ${{ secrets.MONGO_URI }}
      - run: npm test
        env:
          CI: true         
          
      - run: pwd       
        working-directory: ./

      - name: Publish to GitHub Pages Action
        uses: qoomon/actions-publish-to-github-pages@v1.0.3
        with:
          GITHUB_PAGES_SOURCE_DIR: dist # default value:  dist
          GITHUB_PAGES_BRANCH: gh-pages # default value:  gh-pages
          GITHUB_PAGES_REPLACE: false   # default value:  false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        