
name: Node.js CI

on:
  push:
    branches: "master"
  
env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

permissions: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./

    - name: npm install
      run: npm install

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.9.0
      with:
        mongodb-version: '4.4'

    - run: pwd       
      working-directory: ./      
                 
   
 
